### ISSUE TITLE
design review

### ISSUE THREAD

**Issue by Shannafdnd** [Lutrian1/all-human-accessible-website#9]
## Feedback
- Je design is goed uitgedacht en je kan je eigen ideeën erg goed overbrengen. (dit kan je gebruiken als bewijslast voor 1.3.2) Je veranderingen zijn logisch en je kan goed verwoorden waarom je bepaalde keuzes hebt gemaakt. 
- Het is goed dat je em wilt gebruiken voor de tekst
- Je hoeft geen grid te gebruiken voor de 2 lijsten in de nav
- De tekst is gecentreerd in je vorige design, wat in principe niet volgens design standaarden is, maar ik zou dit niet veranderen omdat de titel ook gecentreerd is. Zolang je zorgt dat tekst niet langer is dan ongeveer 12 woorden per regel, is het oke. Hier een bron daarover. (https://imperavi.com/books/ui-typography/basis/line-length/#:~:text=Typically%2060%20to%2080%20characters,in%20English%20for%20any%20UI.)

**Comment by Lutrian1** [comment]
![377832336-b107e5e9-1478-4cbe-9f15-9d168adcb237](https://github.com/user-attachments/assets/fc7d49ca-6647-4d03-8328-2f0bd73415d9)
